// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261010041936_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ParadaRuta", b =>
                {
                    b.Property<Guid>("RutaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("RutaId", "PedidoId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("ParadasRuta", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ClienteTelefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("EntregadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraEntrega")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset>("RegistradoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RutaId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.HasIndex("Ubicacion");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Ubicacion"), "gist");

                    b.HasIndex("ZonaId");

                    b.HasIndex("FechaEntrega", "ZonaId", "Estado");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Repartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.ToTable("Repartidores", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FinalizadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IniciadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.HasIndex("RepartidorId", "Fecha")
                        .IsUnique()
                        .HasFilter("\"Estado\" IN ('Planificada', 'EnCurso')");

                    b.HasIndex("Fecha", "ZonaId", "Estado");

                    b.ToTable("Rutas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPedidosPorRuta")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Polygon>("_poligono")
                        .IsRequired()
                        .HasColumnType("geometry (polygon, 4326)")
                        .HasColumnName("Poligono");

                    b.HasKey("Id");

                    b.HasIndex("Activa");

                    b.ToTable("Zonas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ParadaRuta", b =>
                {
                    b.HasOne("Domain.Entities.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ruta", null)
                        .WithMany("Paradas")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Domain.Entities.Zona", null)
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Ruta", b =>
                {
                    b.HasOne("Domain.Entities.Repartidor", null)
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Zona", null)
                        .WithMany()
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Ruta", b =>
                {
                    b.Navigation("Paradas");
                });
#pragma warning restore 612, 618
        }
    }
}
